import { describe, expect, it, vi, afterEach } from 'vitest';
import { buildBackupPayload, downloadCloudBackup, isValidBackupPayload, requestGoogleAccessToken } from './googleDriveService';
import { DEFAULT_SETTINGS } from './storageService';

describe('Google Drive backup validation', () => {
  afterEach(() => vi.restoreAllMocks());

  it('accepts payload generated by the application', () => {
    const payload = buildBackupPayload(DEFAULT_SETTINGS, [], {}, null);
    expect(isValidBackupPayload(payload)).toBe(true);
    expect(payload.data.settings.customApiKey).toBeUndefined();
  });

  it('rejects invalid positions, enums, and record keys', () => {
    const invalidPosition = buildBackupPayload(DEFAULT_SETTINGS, [], {}, null);
    invalidPosition.data.lastRead = { surahNumber: 115, surahName: 'Invalid', verseNumber: 1, timestamp: new Date().toISOString() };
    expect(isValidBackupPayload(invalidPosition)).toBe(false);

    const invalidTheme = buildBackupPayload(DEFAULT_SETTINGS, [], {}, null);
    invalidTheme.data.settings.theme = 'invalid' as never;
    expect(isValidBackupPayload(invalidTheme)).toBe(false);

    const invalidRecord = buildBackupPayload(DEFAULT_SETTINGS, [], {}, null);
    invalidRecord.data.hafalanRecords.wrong = { surahNumber: 1, verseNumber: 1, status: 'memorized', repeatCount: 1 };
    expect(isValidBackupPayload(invalidRecord)).toBe(false);
  });

  it('uses the configured environment Client ID and stores the returned token in session only', async () => {
    const requestAccessToken = vi.fn();
    const initTokenClient = vi.fn((config) => {
      requestAccessToken.mockImplementation(() => config.callback({ access_token: 'test-token' }));
      return { requestAccessToken };
    });
    window.google = { accounts: { oauth2: { initTokenClient } } };
    await expect(requestGoogleAccessToken()).resolves.toBe('test-token');
    const config = initTokenClient.mock.calls[0][0];
    expect(config.client_id).toBeTruthy();
    expect(config.client_id).not.toContain('your_');
    expect(sessionStorage.getItem('murottal_gdrive_access_token_v1')).toBe('test-token');
    expect(localStorage.getItem('murottal_gdrive_access_token_v1')).toBeNull();
    sessionStorage.clear();
  });

  it('rejects OAuth before opening a token client when Client ID is absent', async () => {
    const initTokenClient = vi.fn();
    window.google = { accounts: { oauth2: { initTokenClient } } };
    await expect(requestGoogleAccessToken('   ')).rejects.toThrow('Google Client ID belum dikonfigurasikan');
    expect(initTokenClient).not.toHaveBeenCalled();
  });

  it('rejects downloads declared larger than 5 MB before reading the body', async () => {
    const text = vi.fn();
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
      ok: true,
      headers: new Headers({ 'content-length': String(5 * 1024 * 1024 + 1) }),
      text
    }));

    await expect(downloadCloudBackup('token', 'file')).rejects.toThrow('melebihi batas 5 MB');
    expect(text).not.toHaveBeenCalled();
  });
});
